# Define the goal
geometry_msgs/PointStamped door_frame_point1  # Specify the two frame points of the door that define the bounding box
geometry_msgs/PointStamped door_frame_point2
---
# Define the result
geometry_msgs/PointStamped handle_edge_point1 # Edge points of the handle
geometry_msgs/PointStamped handle_edge_point2
---
# Define a feedback message
uint32 tbd
