string name
geometry_msgs/Point position

bool is_waving

bool is_pointing
geometry_msgs/Pose pointing_pose

uint8 GENDER_UNKNOWN=0
uint8 GENDER_MALE=1
uint8 GENDER_FEMALE=1
uint8 gender

uint8 age

uint8 COLOR_BLACK=0
uint8 COLOR_BLUE=1
uint8 COLOR_BROWN=2
uint8 COLOR_GREY=3
uint8 COLOR_GREEN=4
uint8 COLOR_ORANGE=5
uint8 COLOR_PINK=6
uint8 COLOR_PURPLE=7
uint8 COLOR_RED=8
uint8 COLOR_WHITE=9
uint8 COLOR_YELLOW=10
uint8 shirt_color
